// Copyright (C) 2026 Rusty LSL contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Consumer-facing explicit runtime operations and activation contracts.
//!
//! This is an additive plane facade over the crate-root compatibility surface.
//! It defines no types, defaults, effects, or authority.

pub use crate::{
    admit_runtime_activation, connect_selected_typed_udp_discovery_double64_session_inlet,
    connect_selected_typed_udp_discovery_float32_session_inlet,
    connect_selected_typed_udp_discovery_int16_session_inlet,
    connect_selected_typed_udp_discovery_int32_session_inlet,
    connect_selected_typed_udp_discovery_int64_session_inlet,
    connect_selected_typed_udp_discovery_int8_session_inlet,
    connect_selected_typed_udp_discovery_string_session_inlet,
    resolve_selected_typed_udp_discovery_float32_session_inlet,
    run_bounded_float32_recovery_clock_queue, run_finite_sample_recovery,
    run_fixed_width_numeric_inlet, run_fixed_width_numeric_outlet, run_integrated_clock_correction,
    run_selected_typed_udp_discovery_double64_session_inlet,
    run_selected_typed_udp_discovery_float32_inlet_session_batch_recovery_clock_queue,
    run_selected_typed_udp_discovery_float32_session_inlet,
    run_selected_typed_udp_discovery_int16_session_inlet,
    run_selected_typed_udp_discovery_int32_session_inlet,
    run_selected_typed_udp_discovery_int64_session_inlet,
    run_selected_typed_udp_discovery_int8_session_inlet,
    run_selected_typed_udp_discovery_string_session_inlet, run_short_info_responder,
    run_stream_inlet_handshake, run_stream_outlet_handshake,
    run_timestamped_double64_bounded_chunk_inlet, run_timestamped_double64_bounded_chunk_outlet,
    run_timestamped_float32_bounded_chunk_inlet, run_timestamped_float32_bounded_chunk_outlet,
    run_timestamped_float32_inlet, run_timestamped_float32_outlet,
    run_timestamped_float32_two_record_chunk_inlet,
    run_timestamped_float32_two_record_chunk_outlet, run_timestamped_int16_bounded_chunk_inlet,
    run_timestamped_int16_bounded_chunk_outlet, run_timestamped_int32_bounded_chunk_inlet,
    run_timestamped_int32_bounded_chunk_outlet, run_timestamped_int64_bounded_chunk_inlet,
    run_timestamped_int64_bounded_chunk_outlet, run_timestamped_int8_bounded_chunk_inlet,
    run_timestamped_int8_bounded_chunk_outlet, run_timestamped_string_bounded_chunk_inlet,
    run_timestamped_string_bounded_chunk_outlet, run_udp_discovery,
    BoundedFloat32PipelineCancellation, BoundedFloat32PipelineError, BoundedFloat32PipelineOutcome,
    BoundedSampleQueue, BoundedSampleQueueActivation, BoundedSampleQueueActivationError,
    BoundedSampleQueueCloseError, BoundedSampleQueueCreateError, BoundedSampleQueuePopError,
    BoundedSampleQueuePushError, BoundedSampleQueueWait, BoundedSampleQueueWaitError, ClockSource,
    FiniteSampleRecoveryActivation, FiniteSampleRecoveryActivationError, FiniteSampleRecoveryError,
    FiniteSampleRecoveryOutcome, FiniteSampleRecoveryPolicy, FiniteSampleRecoveryPolicyError,
    FiniteSampleRecoveryState, FixedWidthNumericRecord, FixedWidthNumericSampleActivation,
    FixedWidthNumericSampleActivationError, FixedWidthNumericSampleError,
    FixedWidthNumericSampleLimitError, FixedWidthNumericSampleLimits, FixedWidthNumericValue,
    IntegratedClockCorrection, IntegratedClockCorrectionActivation,
    IntegratedClockCorrectionActivationError, IntegratedClockCorrectionConfig,
    IntegratedClockCorrectionConfigError, IntegratedClockCorrectionError, RecoveryAttemptFailure,
    RecoveryFailureClass, ResolvedTypedUdpDiscoveryFloat32Session, RuntimeActivationAdmission,
    RuntimeActivationError, RuntimeActivationOutcome, RuntimeActivationReceipt,
    RuntimeActivationSelection, RuntimeModule, RuntimeModuleCapability,
    SelectedTypedUdpDiscoveryFloat32SessionBatchError,
    SelectedTypedUdpDiscoveryFloat32SessionBatchErrorKind,
    SelectedTypedUdpDiscoveryFloat32SessionBatchOutcome, ShortInfoResponderActivation,
    ShortInfoResponderActivationError, ShortInfoResponderError, ShortInfoResponderLimitError,
    ShortInfoResponderLimits, ShortInfoResponderRun, ShortInfoResponderTermination,
    StreamHandshakeActivation, StreamHandshakeActivationError, StreamHandshakeError,
    StreamHandshakeIdentity, StreamHandshakeIdentityError, StreamHandshakeIdentityRole,
    StreamHandshakeLimitError, StreamHandshakeLimits, StreamInletHandshake, StreamOutletHandshake,
    TimestampedDouble64AcceptedOutletSession, TimestampedDouble64BoundedChunkError,
    TimestampedDouble64BoundedChunkInletSessionReport,
    TimestampedDouble64BoundedChunkOutletSessionReport, TimestampedDouble64ConnectedInletSession,
    TimestampedDouble64InletSession, TimestampedDouble64InletSessionReport,
    TimestampedDouble64OutletSession, TimestampedDouble64OutletSessionReport,
    TimestampedDouble64SessionError, TimestampedDouble64SessionIncomplete,
    TimestampedDouble64SessionIoLimitError, TimestampedDouble64SessionIoLimits,
    TimestampedDouble64SessionLimitError, TimestampedDouble64SessionLimits,
    TimestampedDouble64SessionPreflightError, TimestampedDouble64SessionTransferError,
    TimestampedFloat32AcceptedOutletSession, TimestampedFloat32BoundedChunkError,
    TimestampedFloat32BoundedChunkInletSessionReport,
    TimestampedFloat32BoundedChunkOutletSessionReport, TimestampedFloat32ConnectedInletSession,
    TimestampedFloat32InletSession, TimestampedFloat32InletSessionReport,
    TimestampedFloat32OutletSession, TimestampedFloat32OutletSessionReport,
    TimestampedFloat32SampleActivation, TimestampedFloat32SampleActivationError,
    TimestampedFloat32SampleError, TimestampedFloat32SampleLimitError,
    TimestampedFloat32SampleLimits, TimestampedFloat32SessionCompletion,
    TimestampedFloat32SessionError, TimestampedFloat32SessionIncomplete,
    TimestampedFloat32SessionLimitError, TimestampedFloat32SessionLimits,
    TimestampedFloat32SessionPreflightError, TimestampedFloat32SessionRole,
    TimestampedFloat32SessionTransferError, TimestampedFloat32TwoRecordChunkAcceptedOutletSession,
    TimestampedFloat32TwoRecordChunkConnectedInletSession, TimestampedFloat32TwoRecordChunkError,
    TimestampedFloat32TwoRecordChunkInletSession,
    TimestampedFloat32TwoRecordChunkInletSessionReport, TimestampedFloat32TwoRecordChunkLimitError,
    TimestampedFloat32TwoRecordChunkLimits, TimestampedFloat32TwoRecordChunkOutletSession,
    TimestampedFloat32TwoRecordChunkOutletSessionReport, TimestampedInt16AcceptedOutletSession,
    TimestampedInt16BoundedChunkError, TimestampedInt16BoundedChunkInletSessionReport,
    TimestampedInt16BoundedChunkOutletSessionReport, TimestampedInt16ConnectedInletSession,
    TimestampedInt16InletSession, TimestampedInt16InletSessionReport,
    TimestampedInt16OutletSession, TimestampedInt16OutletSessionReport,
    TimestampedInt16SessionError, TimestampedInt16SessionIncomplete,
    TimestampedInt16SessionIoLimitError, TimestampedInt16SessionIoLimits,
    TimestampedInt16SessionLimitError, TimestampedInt16SessionLimits,
    TimestampedInt16SessionPreflightError, TimestampedInt16SessionTransferError,
    TimestampedInt32AcceptedOutletSession, TimestampedInt32BoundedChunkError,
    TimestampedInt32BoundedChunkInletSessionReport,
    TimestampedInt32BoundedChunkOutletSessionReport, TimestampedInt32ConnectedInletSession,
    TimestampedInt32InletSession, TimestampedInt32InletSessionReport,
    TimestampedInt32OutletSession, TimestampedInt32OutletSessionReport,
    TimestampedInt32SessionError, TimestampedInt32SessionIncomplete,
    TimestampedInt32SessionIoLimitError, TimestampedInt32SessionIoLimits,
    TimestampedInt32SessionLimitError, TimestampedInt32SessionLimits,
    TimestampedInt32SessionPreflightError, TimestampedInt32SessionTransferError,
    TimestampedInt64AcceptedOutletSession, TimestampedInt64BoundedChunkError,
    TimestampedInt64BoundedChunkInletSessionReport,
    TimestampedInt64BoundedChunkOutletSessionReport, TimestampedInt64ConnectedInletSession,
    TimestampedInt64InletSession, TimestampedInt64InletSessionReport,
    TimestampedInt64OutletSession, TimestampedInt64OutletSessionReport,
    TimestampedInt64SessionError, TimestampedInt64SessionIncomplete,
    TimestampedInt64SessionIoLimitError, TimestampedInt64SessionIoLimits,
    TimestampedInt64SessionLimitError, TimestampedInt64SessionLimits,
    TimestampedInt64SessionPreflightError, TimestampedInt64SessionTransferError,
    TimestampedInt8AcceptedOutletSession, TimestampedInt8BoundedChunkError,
    TimestampedInt8BoundedChunkInletSessionReport, TimestampedInt8BoundedChunkOutletSessionReport,
    TimestampedInt8ConnectedInletSession, TimestampedInt8InletSession,
    TimestampedInt8InletSessionReport, TimestampedInt8OutletSession,
    TimestampedInt8OutletSessionReport, TimestampedInt8SessionError,
    TimestampedInt8SessionIncomplete, TimestampedInt8SessionIoLimitError,
    TimestampedInt8SessionIoLimits, TimestampedInt8SessionLimitError, TimestampedInt8SessionLimits,
    TimestampedInt8SessionPreflightError, TimestampedInt8SessionTransferError,
    TimestampedStringAcceptedOutletSession, TimestampedStringBoundedChunkError,
    TimestampedStringBoundedChunkInletSessionReport,
    TimestampedStringBoundedChunkOutletSessionReport, TimestampedStringConnectedInletSession,
    TimestampedStringInletSession, TimestampedStringInletSessionReport,
    TimestampedStringOutletSession, TimestampedStringOutletSessionReport,
    TimestampedStringSessionCompletion, TimestampedStringSessionError,
    TimestampedStringSessionIncomplete, TimestampedStringSessionLimitError,
    TimestampedStringSessionLimits, TimestampedStringSessionPreflightError,
    TimestampedStringSessionRole, TimestampedStringSessionTransferError,
    TypedUdpDiscoveryDouble64SessionConnectionError,
    TypedUdpDiscoveryFloat32SessionConnectionError, TypedUdpDiscoveryInt16SessionConnectionError,
    TypedUdpDiscoveryInt32SessionConnectionError, TypedUdpDiscoveryInt64SessionConnectionError,
    TypedUdpDiscoveryInt8SessionConnectionError, TypedUdpDiscoveryStringSessionConnectionError,
    UdpDiscoveryActivation, UdpDiscoveryActivationError, UdpDiscoveryConfig, UdpDiscoveryError,
    UdpDiscoveryLimitError, UdpDiscoveryLimits, UdpDiscoveryResponse, UdpDiscoveryRun,
    UdpDiscoveryTermination, ACCEPTED_FEATURE_LOCK_FINGERPRINT, ACCEPTED_FEATURE_LOCK_REVISION,
    BOUNDED_SAMPLE_QUEUE_EFFECTIVE_MARKER, BOUNDED_SAMPLE_QUEUE_FEATURE_ID,
    FINITE_SAMPLE_RECOVERY_EFFECTIVE_MARKER, FINITE_SAMPLE_RECOVERY_FEATURE_ID,
    FIXED_WIDTH_NUMERIC_SAMPLE_EFFECTIVE_MARKER, FIXED_WIDTH_NUMERIC_SAMPLE_FEATURE_ID,
    INTEGRATED_CLOCK_CORRECTION_EFFECTIVE_MARKER, INTEGRATED_CLOCK_CORRECTION_FEATURE_ID,
    SHORT_INFO_RESPONDER_EFFECTIVE_MARKER, SHORT_INFO_RESPONDER_FEATURE_ID,
    STREAM_HANDSHAKE_EFFECTIVE_MARKER, STREAM_HANDSHAKE_FEATURE_ID,
    TIMESTAMPED_FLOAT32_SAMPLE_EFFECTIVE_MARKER, TIMESTAMPED_FLOAT32_SAMPLE_FEATURE_ID,
    UDP_DISCOVERY_EFFECTIVE_MARKER, UDP_DISCOVERY_FEATURE_ID,
};

pub use crate::{
    run_float32_inlet_session_report_batch_recovery_clock_queue,
    run_float32_inlet_session_report_recovery_clock_queue, Float32SessionBatchHealth,
    Float32SessionBatchHealthClassification, Float32SessionReportAcquisitionTermination,
    Float32SessionReportBatchError, Float32SessionReportBatchOutcome,
    Float32SessionReportBatchTermination, Float32SessionReportPipelineError,
    Float32SessionReportPipelineOutcome, Float32SessionReportRecordOutcome,
};
